name: Build Qt Project

on:
  push:
    branches:
      - develop
      - feature/develop/task3
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '5.15.2'  # Виберіть вашу версію Qt
        host: windows
        target: desktop
        arch: 'win64_msvc2019'  # Використовуємо MSVC для білду на Windows

    - name: Install dependencies
      run: |
        choco install ninja
        choco install cmake
        choco install msvc

    - name: Configure the project
      run: |
        mkdir build
        cd build
        cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="C:/Qt/5.15.2/msvc2019_64" ..

    - name: Build the project
      run: |
        cd build
        cmake --build .

    - name: Save build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: lab3-binary
        path: |
          build/Client_Lab_3/lab3.exe  # Тут треба вказати шлях до бінарника, який генерується

