name: Build Qt Project

on:
  push:
    branches:
      - develop
      - feature/develop/task3
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Qt
      uses: supermarin/qt-action@v1.0.0
      with:
        qt-version: '5.8.0' 
        cmake: false

    - name: Build with qmake
      run: |
        cd src/win/Client_Lab_3
        qmake
        nmake 

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Client_Lab_3_Build
        path: src/win/Client_Lab_3/release/lab3.exe

