name: Build Qt Project

on:
  push:
    branches:
      - develop
      - feature/develop/task3
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.8.0'
        host: windows
        target: desktop
        arch: 'win64_msvc2022_64'

    - name: List available Qt installations
      run: |
        aqt list-qt windows desktop --arch 6.8.0
        


    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_PREFIX_PATH=$HOME/Qt/5.15.2/gcc_64 ../src/win/lab3_cmake

    - name: Build Project
      run: |
        cd build
        cmake --build . --config Release


      
    - name: Save build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: lab3-client-executable
        path: build/** 

